// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datanode.proto

#include "datanode.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace datanode_proto {
PROTOBUF_CONSTEXPR CheckaliveCMD::CheckaliveCMD(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CheckaliveCMDDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckaliveCMDDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckaliveCMDDefaultTypeInternal() {}
  union {
    CheckaliveCMD _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckaliveCMDDefaultTypeInternal _CheckaliveCMD_default_instance_;
PROTOBUF_CONSTEXPR RequestResult::RequestResult(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/false
  , /*decltype(_impl_.valuesizebytes_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RequestResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestResultDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestResultDefaultTypeInternal() {}
  union {
    RequestResult _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestResultDefaultTypeInternal _RequestResult_default_instance_;
PROTOBUF_CONSTEXPR SetInfo::SetInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.block_key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.proxy_ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.block_size_)*/0
  , /*decltype(_impl_.proxy_port_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SetInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetInfoDefaultTypeInternal() {}
  union {
    SetInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetInfoDefaultTypeInternal _SetInfo_default_instance_;
PROTOBUF_CONSTEXPR GetInfo::GetInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.block_key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.proxy_ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.block_size_)*/0
  , /*decltype(_impl_.proxy_port_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetInfoDefaultTypeInternal() {}
  union {
    GetInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetInfoDefaultTypeInternal _GetInfo_default_instance_;
PROTOBUF_CONSTEXPR DelInfo::DelInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.block_key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DelInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DelInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DelInfoDefaultTypeInternal() {}
  union {
    DelInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DelInfoDefaultTypeInternal _DelInfo_default_instance_;
}  // namespace datanode_proto
static ::_pb::Metadata file_level_metadata_datanode_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_datanode_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_datanode_2eproto = nullptr;

const uint32_t TableStruct_datanode_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::datanode_proto::CheckaliveCMD, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::datanode_proto::CheckaliveCMD, _impl_.name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::datanode_proto::RequestResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::datanode_proto::RequestResult, _impl_.message_),
  PROTOBUF_FIELD_OFFSET(::datanode_proto::RequestResult, _impl_.valuesizebytes_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::datanode_proto::SetInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::datanode_proto::SetInfo, _impl_.block_key_),
  PROTOBUF_FIELD_OFFSET(::datanode_proto::SetInfo, _impl_.block_size_),
  PROTOBUF_FIELD_OFFSET(::datanode_proto::SetInfo, _impl_.proxy_ip_),
  PROTOBUF_FIELD_OFFSET(::datanode_proto::SetInfo, _impl_.proxy_port_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::datanode_proto::GetInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::datanode_proto::GetInfo, _impl_.block_key_),
  PROTOBUF_FIELD_OFFSET(::datanode_proto::GetInfo, _impl_.block_size_),
  PROTOBUF_FIELD_OFFSET(::datanode_proto::GetInfo, _impl_.proxy_ip_),
  PROTOBUF_FIELD_OFFSET(::datanode_proto::GetInfo, _impl_.proxy_port_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::datanode_proto::DelInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::datanode_proto::DelInfo, _impl_.block_key_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::datanode_proto::CheckaliveCMD)},
  { 7, -1, -1, sizeof(::datanode_proto::RequestResult)},
  { 15, -1, -1, sizeof(::datanode_proto::SetInfo)},
  { 25, -1, -1, sizeof(::datanode_proto::GetInfo)},
  { 35, -1, -1, sizeof(::datanode_proto::DelInfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::datanode_proto::_CheckaliveCMD_default_instance_._instance,
  &::datanode_proto::_RequestResult_default_instance_._instance,
  &::datanode_proto::_SetInfo_default_instance_._instance,
  &::datanode_proto::_GetInfo_default_instance_._instance,
  &::datanode_proto::_DelInfo_default_instance_._instance,
};

const char descriptor_table_protodef_datanode_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016datanode.proto\022\016datanode_proto\"\035\n\rChec"
  "kaliveCMD\022\014\n\004name\030\001 \001(\t\"8\n\rRequestResult"
  "\022\017\n\007message\030\001 \001(\010\022\026\n\016valuesizebytes\030\002 \001("
  "\005\"V\n\007SetInfo\022\021\n\tblock_key\030\001 \001(\t\022\022\n\nblock"
  "_size\030\002 \001(\005\022\020\n\010proxy_ip\030\003 \001(\t\022\022\n\nproxy_p"
  "ort\030\004 \001(\005\"V\n\007GetInfo\022\021\n\tblock_key\030\001 \001(\t\022"
  "\022\n\nblock_size\030\002 \001(\005\022\020\n\010proxy_ip\030\003 \001(\t\022\022\n"
  "\nproxy_port\030\004 \001(\005\"\034\n\007DelInfo\022\021\n\tblock_ke"
  "y\030\001 \001(\t2\257\002\n\017datanodeService\022J\n\ncheckaliv"
  "e\022\035.datanode_proto.CheckaliveCMD\032\035.datan"
  "ode_proto.RequestResult\022C\n\thandleSet\022\027.d"
  "atanode_proto.SetInfo\032\035.datanode_proto.R"
  "equestResult\022C\n\thandleGet\022\027.datanode_pro"
  "to.GetInfo\032\035.datanode_proto.RequestResul"
  "t\022F\n\014handleDelete\022\027.datanode_proto.DelIn"
  "fo\032\035.datanode_proto.RequestResultb\006proto"
  "3"
  ;
static ::_pbi::once_flag descriptor_table_datanode_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_datanode_2eproto = {
    false, false, 641, descriptor_table_protodef_datanode_2eproto,
    "datanode.proto",
    &descriptor_table_datanode_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_datanode_2eproto::offsets,
    file_level_metadata_datanode_2eproto, file_level_enum_descriptors_datanode_2eproto,
    file_level_service_descriptors_datanode_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_datanode_2eproto_getter() {
  return &descriptor_table_datanode_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_datanode_2eproto(&descriptor_table_datanode_2eproto);
namespace datanode_proto {

// ===================================================================

class CheckaliveCMD::_Internal {
 public:
};

CheckaliveCMD::CheckaliveCMD(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:datanode_proto.CheckaliveCMD)
}
CheckaliveCMD::CheckaliveCMD(const CheckaliveCMD& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CheckaliveCMD* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:datanode_proto.CheckaliveCMD)
}

inline void CheckaliveCMD::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CheckaliveCMD::~CheckaliveCMD() {
  // @@protoc_insertion_point(destructor:datanode_proto.CheckaliveCMD)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CheckaliveCMD::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
}

void CheckaliveCMD::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CheckaliveCMD::Clear() {
// @@protoc_insertion_point(message_clear_start:datanode_proto.CheckaliveCMD)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CheckaliveCMD::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "datanode_proto.CheckaliveCMD.name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CheckaliveCMD::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:datanode_proto.CheckaliveCMD)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "datanode_proto.CheckaliveCMD.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:datanode_proto.CheckaliveCMD)
  return target;
}

size_t CheckaliveCMD::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:datanode_proto.CheckaliveCMD)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CheckaliveCMD::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CheckaliveCMD::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CheckaliveCMD::GetClassData() const { return &_class_data_; }


void CheckaliveCMD::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CheckaliveCMD*>(&to_msg);
  auto& from = static_cast<const CheckaliveCMD&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:datanode_proto.CheckaliveCMD)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CheckaliveCMD::CopyFrom(const CheckaliveCMD& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:datanode_proto.CheckaliveCMD)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CheckaliveCMD::IsInitialized() const {
  return true;
}

void CheckaliveCMD::InternalSwap(CheckaliveCMD* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata CheckaliveCMD::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datanode_2eproto_getter, &descriptor_table_datanode_2eproto_once,
      file_level_metadata_datanode_2eproto[0]);
}

// ===================================================================

class RequestResult::_Internal {
 public:
};

RequestResult::RequestResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:datanode_proto.RequestResult)
}
RequestResult::RequestResult(const RequestResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RequestResult* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.valuesizebytes_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.message_, &from._impl_.message_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.valuesizebytes_) -
    reinterpret_cast<char*>(&_impl_.message_)) + sizeof(_impl_.valuesizebytes_));
  // @@protoc_insertion_point(copy_constructor:datanode_proto.RequestResult)
}

inline void RequestResult::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){false}
    , decltype(_impl_.valuesizebytes_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RequestResult::~RequestResult() {
  // @@protoc_insertion_point(destructor:datanode_proto.RequestResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RequestResult::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void RequestResult::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RequestResult::Clear() {
// @@protoc_insertion_point(message_clear_start:datanode_proto.RequestResult)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.message_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.valuesizebytes_) -
      reinterpret_cast<char*>(&_impl_.message_)) + sizeof(_impl_.valuesizebytes_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RequestResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool message = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.message_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 valuesizebytes = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.valuesizebytes_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RequestResult::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:datanode_proto.RequestResult)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool message = 1;
  if (this->_internal_message() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_message(), target);
  }

  // int32 valuesizebytes = 2;
  if (this->_internal_valuesizebytes() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_valuesizebytes(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:datanode_proto.RequestResult)
  return target;
}

size_t RequestResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:datanode_proto.RequestResult)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool message = 1;
  if (this->_internal_message() != 0) {
    total_size += 1 + 1;
  }

  // int32 valuesizebytes = 2;
  if (this->_internal_valuesizebytes() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_valuesizebytes());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RequestResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RequestResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RequestResult::GetClassData() const { return &_class_data_; }


void RequestResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RequestResult*>(&to_msg);
  auto& from = static_cast<const RequestResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:datanode_proto.RequestResult)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_message() != 0) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_valuesizebytes() != 0) {
    _this->_internal_set_valuesizebytes(from._internal_valuesizebytes());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RequestResult::CopyFrom(const RequestResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:datanode_proto.RequestResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestResult::IsInitialized() const {
  return true;
}

void RequestResult::InternalSwap(RequestResult* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RequestResult, _impl_.valuesizebytes_)
      + sizeof(RequestResult::_impl_.valuesizebytes_)
      - PROTOBUF_FIELD_OFFSET(RequestResult, _impl_.message_)>(
          reinterpret_cast<char*>(&_impl_.message_),
          reinterpret_cast<char*>(&other->_impl_.message_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RequestResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datanode_2eproto_getter, &descriptor_table_datanode_2eproto_once,
      file_level_metadata_datanode_2eproto[1]);
}

// ===================================================================

class SetInfo::_Internal {
 public:
};

SetInfo::SetInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:datanode_proto.SetInfo)
}
SetInfo::SetInfo(const SetInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SetInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.block_key_){}
    , decltype(_impl_.proxy_ip_){}
    , decltype(_impl_.block_size_){}
    , decltype(_impl_.proxy_port_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.block_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.block_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_block_key().empty()) {
    _this->_impl_.block_key_.Set(from._internal_block_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.proxy_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.proxy_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_proxy_ip().empty()) {
    _this->_impl_.proxy_ip_.Set(from._internal_proxy_ip(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.block_size_, &from._impl_.block_size_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.proxy_port_) -
    reinterpret_cast<char*>(&_impl_.block_size_)) + sizeof(_impl_.proxy_port_));
  // @@protoc_insertion_point(copy_constructor:datanode_proto.SetInfo)
}

inline void SetInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.block_key_){}
    , decltype(_impl_.proxy_ip_){}
    , decltype(_impl_.block_size_){0}
    , decltype(_impl_.proxy_port_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.block_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.block_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.proxy_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.proxy_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SetInfo::~SetInfo() {
  // @@protoc_insertion_point(destructor:datanode_proto.SetInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SetInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.block_key_.Destroy();
  _impl_.proxy_ip_.Destroy();
}

void SetInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SetInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:datanode_proto.SetInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.block_key_.ClearToEmpty();
  _impl_.proxy_ip_.ClearToEmpty();
  ::memset(&_impl_.block_size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.proxy_port_) -
      reinterpret_cast<char*>(&_impl_.block_size_)) + sizeof(_impl_.proxy_port_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SetInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string block_key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_block_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "datanode_proto.SetInfo.block_key"));
        } else
          goto handle_unusual;
        continue;
      // int32 block_size = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.block_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string proxy_ip = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_proxy_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "datanode_proto.SetInfo.proxy_ip"));
        } else
          goto handle_unusual;
        continue;
      // int32 proxy_port = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.proxy_port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SetInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:datanode_proto.SetInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string block_key = 1;
  if (!this->_internal_block_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_block_key().data(), static_cast<int>(this->_internal_block_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "datanode_proto.SetInfo.block_key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_block_key(), target);
  }

  // int32 block_size = 2;
  if (this->_internal_block_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_block_size(), target);
  }

  // string proxy_ip = 3;
  if (!this->_internal_proxy_ip().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_proxy_ip().data(), static_cast<int>(this->_internal_proxy_ip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "datanode_proto.SetInfo.proxy_ip");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_proxy_ip(), target);
  }

  // int32 proxy_port = 4;
  if (this->_internal_proxy_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_proxy_port(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:datanode_proto.SetInfo)
  return target;
}

size_t SetInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:datanode_proto.SetInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string block_key = 1;
  if (!this->_internal_block_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_block_key());
  }

  // string proxy_ip = 3;
  if (!this->_internal_proxy_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_proxy_ip());
  }

  // int32 block_size = 2;
  if (this->_internal_block_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_block_size());
  }

  // int32 proxy_port = 4;
  if (this->_internal_proxy_port() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_proxy_port());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SetInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SetInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SetInfo::GetClassData() const { return &_class_data_; }


void SetInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SetInfo*>(&to_msg);
  auto& from = static_cast<const SetInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:datanode_proto.SetInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_block_key().empty()) {
    _this->_internal_set_block_key(from._internal_block_key());
  }
  if (!from._internal_proxy_ip().empty()) {
    _this->_internal_set_proxy_ip(from._internal_proxy_ip());
  }
  if (from._internal_block_size() != 0) {
    _this->_internal_set_block_size(from._internal_block_size());
  }
  if (from._internal_proxy_port() != 0) {
    _this->_internal_set_proxy_port(from._internal_proxy_port());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SetInfo::CopyFrom(const SetInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:datanode_proto.SetInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetInfo::IsInitialized() const {
  return true;
}

void SetInfo::InternalSwap(SetInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.block_key_, lhs_arena,
      &other->_impl_.block_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.proxy_ip_, lhs_arena,
      &other->_impl_.proxy_ip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SetInfo, _impl_.proxy_port_)
      + sizeof(SetInfo::_impl_.proxy_port_)
      - PROTOBUF_FIELD_OFFSET(SetInfo, _impl_.block_size_)>(
          reinterpret_cast<char*>(&_impl_.block_size_),
          reinterpret_cast<char*>(&other->_impl_.block_size_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SetInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datanode_2eproto_getter, &descriptor_table_datanode_2eproto_once,
      file_level_metadata_datanode_2eproto[2]);
}

// ===================================================================

class GetInfo::_Internal {
 public:
};

GetInfo::GetInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:datanode_proto.GetInfo)
}
GetInfo::GetInfo(const GetInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.block_key_){}
    , decltype(_impl_.proxy_ip_){}
    , decltype(_impl_.block_size_){}
    , decltype(_impl_.proxy_port_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.block_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.block_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_block_key().empty()) {
    _this->_impl_.block_key_.Set(from._internal_block_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.proxy_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.proxy_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_proxy_ip().empty()) {
    _this->_impl_.proxy_ip_.Set(from._internal_proxy_ip(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.block_size_, &from._impl_.block_size_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.proxy_port_) -
    reinterpret_cast<char*>(&_impl_.block_size_)) + sizeof(_impl_.proxy_port_));
  // @@protoc_insertion_point(copy_constructor:datanode_proto.GetInfo)
}

inline void GetInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.block_key_){}
    , decltype(_impl_.proxy_ip_){}
    , decltype(_impl_.block_size_){0}
    , decltype(_impl_.proxy_port_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.block_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.block_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.proxy_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.proxy_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GetInfo::~GetInfo() {
  // @@protoc_insertion_point(destructor:datanode_proto.GetInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.block_key_.Destroy();
  _impl_.proxy_ip_.Destroy();
}

void GetInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:datanode_proto.GetInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.block_key_.ClearToEmpty();
  _impl_.proxy_ip_.ClearToEmpty();
  ::memset(&_impl_.block_size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.proxy_port_) -
      reinterpret_cast<char*>(&_impl_.block_size_)) + sizeof(_impl_.proxy_port_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string block_key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_block_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "datanode_proto.GetInfo.block_key"));
        } else
          goto handle_unusual;
        continue;
      // int32 block_size = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.block_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string proxy_ip = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_proxy_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "datanode_proto.GetInfo.proxy_ip"));
        } else
          goto handle_unusual;
        continue;
      // int32 proxy_port = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.proxy_port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:datanode_proto.GetInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string block_key = 1;
  if (!this->_internal_block_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_block_key().data(), static_cast<int>(this->_internal_block_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "datanode_proto.GetInfo.block_key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_block_key(), target);
  }

  // int32 block_size = 2;
  if (this->_internal_block_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_block_size(), target);
  }

  // string proxy_ip = 3;
  if (!this->_internal_proxy_ip().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_proxy_ip().data(), static_cast<int>(this->_internal_proxy_ip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "datanode_proto.GetInfo.proxy_ip");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_proxy_ip(), target);
  }

  // int32 proxy_port = 4;
  if (this->_internal_proxy_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_proxy_port(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:datanode_proto.GetInfo)
  return target;
}

size_t GetInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:datanode_proto.GetInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string block_key = 1;
  if (!this->_internal_block_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_block_key());
  }

  // string proxy_ip = 3;
  if (!this->_internal_proxy_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_proxy_ip());
  }

  // int32 block_size = 2;
  if (this->_internal_block_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_block_size());
  }

  // int32 proxy_port = 4;
  if (this->_internal_proxy_port() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_proxy_port());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetInfo::GetClassData() const { return &_class_data_; }


void GetInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetInfo*>(&to_msg);
  auto& from = static_cast<const GetInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:datanode_proto.GetInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_block_key().empty()) {
    _this->_internal_set_block_key(from._internal_block_key());
  }
  if (!from._internal_proxy_ip().empty()) {
    _this->_internal_set_proxy_ip(from._internal_proxy_ip());
  }
  if (from._internal_block_size() != 0) {
    _this->_internal_set_block_size(from._internal_block_size());
  }
  if (from._internal_proxy_port() != 0) {
    _this->_internal_set_proxy_port(from._internal_proxy_port());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetInfo::CopyFrom(const GetInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:datanode_proto.GetInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetInfo::IsInitialized() const {
  return true;
}

void GetInfo::InternalSwap(GetInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.block_key_, lhs_arena,
      &other->_impl_.block_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.proxy_ip_, lhs_arena,
      &other->_impl_.proxy_ip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetInfo, _impl_.proxy_port_)
      + sizeof(GetInfo::_impl_.proxy_port_)
      - PROTOBUF_FIELD_OFFSET(GetInfo, _impl_.block_size_)>(
          reinterpret_cast<char*>(&_impl_.block_size_),
          reinterpret_cast<char*>(&other->_impl_.block_size_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GetInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datanode_2eproto_getter, &descriptor_table_datanode_2eproto_once,
      file_level_metadata_datanode_2eproto[3]);
}

// ===================================================================

class DelInfo::_Internal {
 public:
};

DelInfo::DelInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:datanode_proto.DelInfo)
}
DelInfo::DelInfo(const DelInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DelInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.block_key_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.block_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.block_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_block_key().empty()) {
    _this->_impl_.block_key_.Set(from._internal_block_key(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:datanode_proto.DelInfo)
}

inline void DelInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.block_key_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.block_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.block_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DelInfo::~DelInfo() {
  // @@protoc_insertion_point(destructor:datanode_proto.DelInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DelInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.block_key_.Destroy();
}

void DelInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DelInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:datanode_proto.DelInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.block_key_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DelInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string block_key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_block_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "datanode_proto.DelInfo.block_key"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DelInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:datanode_proto.DelInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string block_key = 1;
  if (!this->_internal_block_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_block_key().data(), static_cast<int>(this->_internal_block_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "datanode_proto.DelInfo.block_key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_block_key(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:datanode_proto.DelInfo)
  return target;
}

size_t DelInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:datanode_proto.DelInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string block_key = 1;
  if (!this->_internal_block_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_block_key());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DelInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DelInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DelInfo::GetClassData() const { return &_class_data_; }


void DelInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DelInfo*>(&to_msg);
  auto& from = static_cast<const DelInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:datanode_proto.DelInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_block_key().empty()) {
    _this->_internal_set_block_key(from._internal_block_key());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DelInfo::CopyFrom(const DelInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:datanode_proto.DelInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DelInfo::IsInitialized() const {
  return true;
}

void DelInfo::InternalSwap(DelInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.block_key_, lhs_arena,
      &other->_impl_.block_key_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata DelInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datanode_2eproto_getter, &descriptor_table_datanode_2eproto_once,
      file_level_metadata_datanode_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace datanode_proto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::datanode_proto::CheckaliveCMD*
Arena::CreateMaybeMessage< ::datanode_proto::CheckaliveCMD >(Arena* arena) {
  return Arena::CreateMessageInternal< ::datanode_proto::CheckaliveCMD >(arena);
}
template<> PROTOBUF_NOINLINE ::datanode_proto::RequestResult*
Arena::CreateMaybeMessage< ::datanode_proto::RequestResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::datanode_proto::RequestResult >(arena);
}
template<> PROTOBUF_NOINLINE ::datanode_proto::SetInfo*
Arena::CreateMaybeMessage< ::datanode_proto::SetInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::datanode_proto::SetInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::datanode_proto::GetInfo*
Arena::CreateMaybeMessage< ::datanode_proto::GetInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::datanode_proto::GetInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::datanode_proto::DelInfo*
Arena::CreateMaybeMessage< ::datanode_proto::DelInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::datanode_proto::DelInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
